---
title: "SMPE Project"
author: "Insaf Boukrouh & Othmane Nahyl"
date: "30 décembre 2017"
output: 
  html_document: 
    fig_height: 7
    fig_width: 9
    highlight: tango
---

## Loading and cleaning the datasets
```{r, message=F, warning=F}
library(plyr)
library(doParallel)
library(ggplot2)
library(grid)
library(gridExtra)

# Register parallel backend in order to load files in parallel
nodes <- detectCores()
cl <- makeCluster(nodes)
registerDoParallel(cl)

# Load the csv files and keep certain columns
cities_data=ldply(list.files(path="../usa-data/",pattern="csv",full.names=TRUE),.parallel = TRUE,function(filename) {
  # Columns to keep
    keeps <- c("id","host_id","host_response_time","host_response_rate","host_acceptance_rate","host_total_listings_count","zipcode","country_code","property_type","room_type","accommodates","bathrooms","bedrooms","beds","bed_type","square_feet","price","security_deposit","cleaning_fee","extra_people","minimum_nights","maximum_nights","number_of_reviews","review_scores_rating","review_scores_accuracy","review_scores_cleanliness","review_scores_checkin","review_scores_communication","review_scores_location","review_scores_value","instant_bookable","cancellation_policy","host_since","calendar_last_scraped","city","state")
    city_data = read.csv(filename)
    city_data <- city_data[keeps]
    
    return(city_data)
})

# Convert host_response_rate from factors to numeric values
cities_data$host_response_rate = as.numeric(gsub("%", "", as.character(cities_data$host_response_rate)))/100

# Convert host_acceptance_rate from factors to numeric values
cities_data$host_acceptance_rate=as.numeric(gsub("%", "", as.character(cities_data$host_acceptance_rate)))/100

# Convert price from factors to numeric values
cities_data$price <- as.double(substring(gsub(",", "", as.character(cities_data$price)),2))

# Convert security_deposit from factors to numeric values
cities_data$security_deposit <- as.double(substring(gsub(",", "", as.character(cities_data$security_deposit)),2))
cities_data$security_deposit[is.na(cities_data$security_deposit)] <- 0

# Convert cleaning_fee from factors to numeric values
cities_data$cleaning_fee <- as.double(substring(gsub(",", "", as.character(cities_data$cleaning_fee)),2))
cities_data$cleaning_fee[is.na(cities_data$cleaning_fee)] <- 0

# Convert extra_people from factors to numeric values
cities_data$extra_people <- as.double(substring(gsub(",", "", as.character(cities_data$extra_people)),2))
cities_data$extra_people[is.na(cities_data$extra_people)] <- 0

summary(cities_data)

ggplot(data = cities_data, aes(x = host_response_time, y = price,color=host_response_time)) + geom_boxplot() +geom_jitter(position=position_jitter(0.3),size=0.1)+ theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

ggplot(data = cities_data, aes(x = host_response_rate, y = price, color=host_response_rate)) + geom_point(size=0.1)

ggplot(data = cities_data, aes(x = host_acceptance_rate, y = price, color=host_acceptance_rate)) +geom_point(size=0.1) 

ggplot(data = cities_data, aes(x = host_total_listings_count, y = price, color=host_total_listings_count)) +geom_point(size=0.1) 

ggplot(data = cities_data, aes(x = property_type, y = price,color=property_type))+ geom_boxplot() +geom_jitter(position=position_jitter(0.3),size=0.1)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(data = cities_data, aes(x = room_type, y = price,color=room_type))+ geom_boxplot() +geom_jitter(position=position_jitter(0.3),size=0.1) + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(data = cities_data, aes(x = accommodates, y = price,color=accommodates)) +geom_jitter(position=position_jitter(0.3),size=0.1) 

ggplot(data = cities_data, aes(x = bathrooms, y = price, color=bathrooms)) +geom_jitter(width = 0.1,height = 0.2,size=0.1) 

ggplot(data = cities_data, aes(x = bedrooms, y = price,color=bedrooms)) +geom_jitter(position=position_jitter(0.3),size=0.1) 

ggplot(data = cities_data, aes(x = beds, y = price,color=beds)) +geom_jitter(position=position_jitter(0.3),size=0.1)

ggplot(data = cities_data, aes(x = bed_type, y = price,color=bed_type))+ geom_boxplot() +geom_jitter(position=position_jitter(0.3),size=0.1)

ggplot(data = cities_data, aes(x = square_feet, y = price,color=square_feet)) +geom_point(size=0.1)

ggplot(data = cities_data, aes(x = minimum_nights, y = price,color=minimum_nights))  +geom_point(size=0.1)

ggplot(data = cities_data, aes(x = maximum_nights, y = price,color=maximum_nights)) +geom_point(size=0.1)

ggplot(data = cities_data, aes(x = instant_bookable, y = price,color=instant_bookable))+ geom_boxplot() +geom_jitter(position=position_jitter(0.3),size=0.1)

ggplot(data = cities_data, aes(x = cancellation_policy, y = price,color=cancellation_policy))+ geom_boxplot() +geom_jitter(position=position_jitter(0.3),size=0.1)

# grid.arrange(p1,p2, ncol = 1)
stopCluster(cl)
```

## Miscellaneous
```{r}
# function: removing lines with NA values in specific columns
completeFun <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}
```

### Incomes
```{r}
# Clean
incomes_data <- completeFun(cities_data, c("price", "minimum_nights", "number_of_reviews", "host_since", "calendar_last_scraped"))

# Calculate the income for each listing
incomes_data$income <- incomes_data$number_of_reviews*incomes_data$minimum_nights*incomes_data$price

# This duration should be the same for listings having the same host 
incomes_data$duration <- abs(as.Date(as.character(incomes_data$calendar_last_scraped), format = "%Y-%m-%d") -
                          as.Date(as.character(incomes_data$host_since), format = "%Y-%m-%d"))/30

# Aggregate the income by host
incomes_data <- aggregate(
    cbind(incomes_data$income, incomes_data$duration),
    by = list(host_id = incomes_data$host_id),
    FUN = function(x) sum(x))

# Calculate the income per month
incomes_data$income_per_month = unlist(incomes_data['V1'])/unlist(incomes_data['V2'])

# Plot
ggplot(incomes_data, aes(x = income_per_month))+
  geom_histogram(color = "darkblue", fill = "lightblue", binwidth = 1000)+
  labs(title = "Incomes in the USA", x = "Income per month", y = "Count")

# TODO: print a more accurate histogram (with limited values)
```

### Type of listings
```{r}
# Get the room types and their percentages
room_types_counts <- table(cities_data$room_type)
room_types <- names(room_types_counts)
counts <- as.vector(room_types_counts)
percentages <- scales::percent(round(counts/sum(counts), 2))
room_types_percentages <- sprintf("%s (%s)", names, percentages)
room_types_counts_df <- data.frame(group = room_types, value = counts)

# Plot
pie <- ggplot(room_types_counts_df, aes(x = "", y = value, fill = room_types_percentages))+
  geom_bar(width = 1, stat = "identity")+
  coord_polar("y", start = 0)+
  scale_fill_brewer("Room Types", palette = "Dark2")+
  ggtitle("Type of listings")+
  ylab("")+
  xlab("")+
  labs(fill="")+
  theme(axis.ticks = element_blank(), panel.grid = element_blank(), axis.text = element_blank())+
  geom_text(aes(label = percentages), size = 5, position = position_stack(vjust = 0.5))
pie
```

### Evolution of new hosts over time
```{r}
# Clean
new_hosts_data <- completeFun(cities_data, c("host_since"))

# Calculate the number of new hosts for each year
new_hosts_data$host_since <- as.Date(new_hosts_data$host_since, '%Y-%m-%d')
new_hosts_data <- new_hosts_data[order(as.Date(new_hosts_data$host_since, format="%Y-%m-%d")),]
new_hosts_data$host_since <- format(as.Date(new_hosts_data$host_since, "%Y-%m-%d"), format="%Y")
new_hosts_data_table <- table(new_hosts_data$host_since)

# Plot
plot(names(new_hosts_data_table ), as.vector(new_hosts_data_table), type = "l", xlab = "Time", ylab = "Number of new hosts")

# TODO Try to plot this by month
# TODO Remove 2017 data since they are not complete
```

### Airbnb Prices
```{r}
trim <- function (x) gsub("^\\s+|\\s+$", "", x)

# Clean
prices_per_state <- completeFun(cities_data, c("price", "state"))
prices_per_state$state <- trim(prices_per_state$state)
prices_per_state <- subset(prices_per_state, prices_per_state$state != '')
prices_per_state$state[prices_per_state$state == 'New York'] <- 'NY'
prices_per_state$state[prices_per_state$state == 'ny'] <- 'NY'
prices_per_state$state[prices_per_state$state == 'Baja California'] <- 'CA'
prices_per_state$state[prices_per_state$state == 'secc Terrazas'] <- 'CA'
prices_per_state$state[prices_per_state$state == 'ca'] <- 'CA'
prices_per_state$state[prices_per_state$state == 'Ca'] <- 'CA'
prices_per_state$state[prices_per_state$state == 'wa'] <- 'WA'
prices_per_state$state[prices_per_state$state == 'il'] <- 'IL'
prices_per_state$state[prices_per_state$state == 'Il'] <- 'IL'

# Calculate the average price per city
prices_per_state <- aggregate(cbind(prices_per_state$price),
                  by = list(state = prices_per_state$state),
                  FUN = function(x) mean(x))

# Plot
ggplot(data = prices_per_state, aes(x = prices_per_state$state, y = prices_per_state$V1))+
    geom_bar(stat = "identity", fill = "steelblue", width = 0.7)+
    geom_text(aes(label = round(prices_per_state$V1, 2)), size=4)+
    coord_flip()+
    xlab("State")+
    ylab("Average Daily Price")+  
    theme_minimal()
```






